class LogAction:
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"

    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"

    VIEW = "VIEW"

    IMPORT = "IMPORT"
    EXPORT = "EXPORT"

    FAILED_LOGIN = "FAILED_LOGIN"

    CHANGE_PASSWORD = "CHANGE_PASSWORD"

    RESET_PASSWORD = "RESET_PASSWORD"